/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FlatmatesRouteImport } from './routes/flatmates'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ListPropertyRouteImport } from './routes/list-property'
import { Route as LocalitiesRouteImport } from './routes/localities'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as RentRouteImport } from './routes/rent'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as TenantRouteImport } from './routes/tenant'
import { Route as DashboardAgentRouteImport } from './routes/dashboard.agent'
import { Route as DashboardOwnerRouteImport } from './routes/dashboard.owner'
import { Route as DashboardTenantRouteImport } from './routes/dashboard.tenant'
import { Route as LegalCommunityGuidelinesRouteImport } from './routes/legal.community-guidelines'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as OwnerInterestsRouteImport } from './routes/owner.interests'
import { Route as OwnerMessagesRouteImport } from './routes/owner.messages'
import { Route as OwnerPropertiesRouteImport } from './routes/owner.properties'
import { Route as OwnerVisitsRouteImport } from './routes/owner.visits'
import { Route as PropertyPropertyIdRouteImport } from './routes/property.$propertyId'
import { Route as TenantInterestsRouteImport } from './routes/tenant.interests'
import { Route as TenantMessagesRouteImport } from './routes/tenant.messages'
import { Route as TenantSavedRouteImport } from './routes/tenant.saved'
import { Route as TenantVisitsRouteImport } from './routes/tenant.visits'
import { Route as OwnerMessagesConversationIdRouteImport } from './routes/owner.messages.$conversationId'
import { Route as PropertyPropertyIdInterestRouteImport } from './routes/property.$propertyId.interest'
import { Route as TenantInterestsInterestIdRouteImport } from './routes/tenant.interests.$interestId'
import { Route as TenantMessagesConversationIdRouteImport } from './routes/tenant.messages.$conversationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FlatmatesRoute = FlatmatesRouteImport.update({
  id: '/flatmates',
  path: '/flatmates',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ListPropertyRoute = ListPropertyRouteImport.update({
  id: '/list-property',
  path: '/list-property',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalitiesRoute = LocalitiesRouteImport.update({
  id: '/localities',
  path: '/localities',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const RentRoute = RentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantRoute = TenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAgentRoute = DashboardAgentRouteImport.update({
  id: '/dashboard/agent',
  path: '/dashboard/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOwnerRoute = DashboardOwnerRouteImport.update({
  id: '/dashboard/owner',
  path: '/dashboard/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTenantRoute = DashboardTenantRouteImport.update({
  id: '/dashboard/tenant',
  path: '/dashboard/tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCommunityGuidelinesRoute =
  LegalCommunityGuidelinesRouteImport.update({
    id: '/legal/community-guidelines',
    path: '/legal/community-guidelines',
    getParentRoute: () => rootRouteImport,
  } as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerInterestsRoute = OwnerInterestsRouteImport.update({
  id: '/interests',
  path: '/interests',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerMessagesRoute = OwnerMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerPropertiesRoute = OwnerPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerVisitsRoute = OwnerVisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => OwnerRoute,
} as any)
const PropertyPropertyIdRoute = PropertyPropertyIdRouteImport.update({
  id: '/property/$propertyId',
  path: '/property/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantInterestsRoute = TenantInterestsRouteImport.update({
  id: '/interests',
  path: '/interests',
  getParentRoute: () => TenantRoute,
} as any)
const TenantMessagesRoute = TenantMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => TenantRoute,
} as any)
const TenantSavedRoute = TenantSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => TenantRoute,
} as any)
const TenantVisitsRoute = TenantVisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => TenantRoute,
} as any)
const OwnerMessagesConversationIdRoute =
  OwnerMessagesConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => OwnerMessagesRoute,
  } as any)
const PropertyPropertyIdInterestRoute =
  PropertyPropertyIdInterestRouteImport.update({
    id: '/interest',
    path: '/interest',
    getParentRoute: () => PropertyPropertyIdRoute,
  } as any)
const TenantInterestsInterestIdRoute =
  TenantInterestsInterestIdRouteImport.update({
    id: '/$interestId',
    path: '/$interestId',
    getParentRoute: () => TenantInterestsRoute,
  } as any)
const TenantMessagesConversationIdRoute =
  TenantMessagesConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => TenantMessagesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agent': typeof AgentRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/flatmates': typeof FlatmatesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/list-property': typeof ListPropertyRoute
  '/localities': typeof LocalitiesRoute
  '/owner': typeof OwnerRouteWithChildren
  '/rent': typeof RentRoute
  '/safety': typeof SafetyRoute
  '/tenant': typeof TenantRouteWithChildren
  '/dashboard/agent': typeof DashboardAgentRoute
  '/dashboard/owner': typeof DashboardOwnerRoute
  '/dashboard/tenant': typeof DashboardTenantRoute
  '/legal/community-guidelines': typeof LegalCommunityGuidelinesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/owner/interests': typeof OwnerInterestsRoute
  '/owner/messages': typeof OwnerMessagesRouteWithChildren
  '/owner/properties': typeof OwnerPropertiesRoute
  '/owner/visits': typeof OwnerVisitsRoute
  '/property/$propertyId': typeof PropertyPropertyIdRouteWithChildren
  '/tenant/interests': typeof TenantInterestsRouteWithChildren
  '/tenant/messages': typeof TenantMessagesRouteWithChildren
  '/tenant/saved': typeof TenantSavedRoute
  '/tenant/visits': typeof TenantVisitsRoute
  '/owner/messages/$conversationId': typeof OwnerMessagesConversationIdRoute
  '/property/$propertyId/interest': typeof PropertyPropertyIdInterestRoute
  '/tenant/interests/$interestId': typeof TenantInterestsInterestIdRoute
  '/tenant/messages/$conversationId': typeof TenantMessagesConversationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agent': typeof AgentRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/flatmates': typeof FlatmatesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/list-property': typeof ListPropertyRoute
  '/localities': typeof LocalitiesRoute
  '/owner': typeof OwnerRouteWithChildren
  '/rent': typeof RentRoute
  '/safety': typeof SafetyRoute
  '/tenant': typeof TenantRouteWithChildren
  '/dashboard/agent': typeof DashboardAgentRoute
  '/dashboard/owner': typeof DashboardOwnerRoute
  '/dashboard/tenant': typeof DashboardTenantRoute
  '/legal/community-guidelines': typeof LegalCommunityGuidelinesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/owner/interests': typeof OwnerInterestsRoute
  '/owner/messages': typeof OwnerMessagesRouteWithChildren
  '/owner/properties': typeof OwnerPropertiesRoute
  '/owner/visits': typeof OwnerVisitsRoute
  '/property/$propertyId': typeof PropertyPropertyIdRouteWithChildren
  '/tenant/interests': typeof TenantInterestsRouteWithChildren
  '/tenant/messages': typeof TenantMessagesRouteWithChildren
  '/tenant/saved': typeof TenantSavedRoute
  '/tenant/visits': typeof TenantVisitsRoute
  '/owner/messages/$conversationId': typeof OwnerMessagesConversationIdRoute
  '/property/$propertyId/interest': typeof PropertyPropertyIdInterestRoute
  '/tenant/interests/$interestId': typeof TenantInterestsInterestIdRoute
  '/tenant/messages/$conversationId': typeof TenantMessagesConversationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agent': typeof AgentRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/flatmates': typeof FlatmatesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/list-property': typeof ListPropertyRoute
  '/localities': typeof LocalitiesRoute
  '/owner': typeof OwnerRouteWithChildren
  '/rent': typeof RentRoute
  '/safety': typeof SafetyRoute
  '/tenant': typeof TenantRouteWithChildren
  '/dashboard/agent': typeof DashboardAgentRoute
  '/dashboard/owner': typeof DashboardOwnerRoute
  '/dashboard/tenant': typeof DashboardTenantRoute
  '/legal/community-guidelines': typeof LegalCommunityGuidelinesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/owner/interests': typeof OwnerInterestsRoute
  '/owner/messages': typeof OwnerMessagesRouteWithChildren
  '/owner/properties': typeof OwnerPropertiesRoute
  '/owner/visits': typeof OwnerVisitsRoute
  '/property/$propertyId': typeof PropertyPropertyIdRouteWithChildren
  '/tenant/interests': typeof TenantInterestsRouteWithChildren
  '/tenant/messages': typeof TenantMessagesRouteWithChildren
  '/tenant/saved': typeof TenantSavedRoute
  '/tenant/visits': typeof TenantVisitsRoute
  '/owner/messages/$conversationId': typeof OwnerMessagesConversationIdRoute
  '/property/$propertyId/interest': typeof PropertyPropertyIdInterestRoute
  '/tenant/interests/$interestId': typeof TenantInterestsInterestIdRoute
  '/tenant/messages/$conversationId': typeof TenantMessagesConversationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agent'
    | '/auth'
    | '/contact'
    | '/flatmates'
    | '/how-it-works'
    | '/list-property'
    | '/localities'
    | '/owner'
    | '/rent'
    | '/safety'
    | '/tenant'
    | '/dashboard/agent'
    | '/dashboard/owner'
    | '/dashboard/tenant'
    | '/legal/community-guidelines'
    | '/legal/privacy'
    | '/legal/terms'
    | '/owner/interests'
    | '/owner/messages'
    | '/owner/properties'
    | '/owner/visits'
    | '/property/$propertyId'
    | '/tenant/interests'
    | '/tenant/messages'
    | '/tenant/saved'
    | '/tenant/visits'
    | '/owner/messages/$conversationId'
    | '/property/$propertyId/interest'
    | '/tenant/interests/$interestId'
    | '/tenant/messages/$conversationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agent'
    | '/auth'
    | '/contact'
    | '/flatmates'
    | '/how-it-works'
    | '/list-property'
    | '/localities'
    | '/owner'
    | '/rent'
    | '/safety'
    | '/tenant'
    | '/dashboard/agent'
    | '/dashboard/owner'
    | '/dashboard/tenant'
    | '/legal/community-guidelines'
    | '/legal/privacy'
    | '/legal/terms'
    | '/owner/interests'
    | '/owner/messages'
    | '/owner/properties'
    | '/owner/visits'
    | '/property/$propertyId'
    | '/tenant/interests'
    | '/tenant/messages'
    | '/tenant/saved'
    | '/tenant/visits'
    | '/owner/messages/$conversationId'
    | '/property/$propertyId/interest'
    | '/tenant/interests/$interestId'
    | '/tenant/messages/$conversationId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agent'
    | '/auth'
    | '/contact'
    | '/flatmates'
    | '/how-it-works'
    | '/list-property'
    | '/localities'
    | '/owner'
    | '/rent'
    | '/safety'
    | '/tenant'
    | '/dashboard/agent'
    | '/dashboard/owner'
    | '/dashboard/tenant'
    | '/legal/community-guidelines'
    | '/legal/privacy'
    | '/legal/terms'
    | '/owner/interests'
    | '/owner/messages'
    | '/owner/properties'
    | '/owner/visits'
    | '/property/$propertyId'
    | '/tenant/interests'
    | '/tenant/messages'
    | '/tenant/saved'
    | '/tenant/visits'
    | '/owner/messages/$conversationId'
    | '/property/$propertyId/interest'
    | '/tenant/interests/$interestId'
    | '/tenant/messages/$conversationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgentRoute: typeof AgentRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FlatmatesRoute: typeof FlatmatesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ListPropertyRoute: typeof ListPropertyRoute
  LocalitiesRoute: typeof LocalitiesRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  RentRoute: typeof RentRoute
  SafetyRoute: typeof SafetyRoute
  TenantRoute: typeof TenantRouteWithChildren
  DashboardAgentRoute: typeof DashboardAgentRoute
  DashboardOwnerRoute: typeof DashboardOwnerRoute
  DashboardTenantRoute: typeof DashboardTenantRoute
  LegalCommunityGuidelinesRoute: typeof LegalCommunityGuidelinesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  PropertyPropertyIdRoute: typeof PropertyPropertyIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flatmates': {
      id: '/flatmates'
      path: '/flatmates'
      fullPath: '/flatmates'
      preLoaderRoute: typeof FlatmatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-property': {
      id: '/list-property'
      path: '/list-property'
      fullPath: '/list-property'
      preLoaderRoute: typeof ListPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/localities': {
      id: '/localities'
      path: '/localities'
      fullPath: '/localities'
      preLoaderRoute: typeof LocalitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent': {
      id: '/rent'
      path: '/rent'
      fullPath: '/rent'
      preLoaderRoute: typeof RentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant': {
      id: '/tenant'
      path: '/tenant'
      fullPath: '/tenant'
      preLoaderRoute: typeof TenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/agent': {
      id: '/dashboard/agent'
      path: '/dashboard/agent'
      fullPath: '/dashboard/agent'
      preLoaderRoute: typeof DashboardAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/owner': {
      id: '/dashboard/owner'
      path: '/dashboard/owner'
      fullPath: '/dashboard/owner'
      preLoaderRoute: typeof DashboardOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tenant': {
      id: '/dashboard/tenant'
      path: '/dashboard/tenant'
      fullPath: '/dashboard/tenant'
      preLoaderRoute: typeof DashboardTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/community-guidelines': {
      id: '/legal/community-guidelines'
      path: '/legal/community-guidelines'
      fullPath: '/legal/community-guidelines'
      preLoaderRoute: typeof LegalCommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/interests': {
      id: '/owner/interests'
      path: '/interests'
      fullPath: '/owner/interests'
      preLoaderRoute: typeof OwnerInterestsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/messages': {
      id: '/owner/messages'
      path: '/messages'
      fullPath: '/owner/messages'
      preLoaderRoute: typeof OwnerMessagesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/properties': {
      id: '/owner/properties'
      path: '/properties'
      fullPath: '/owner/properties'
      preLoaderRoute: typeof OwnerPropertiesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/visits': {
      id: '/owner/visits'
      path: '/visits'
      fullPath: '/owner/visits'
      preLoaderRoute: typeof OwnerVisitsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/property/$propertyId': {
      id: '/property/$propertyId'
      path: '/property/$propertyId'
      fullPath: '/property/$propertyId'
      preLoaderRoute: typeof PropertyPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/interests': {
      id: '/tenant/interests'
      path: '/interests'
      fullPath: '/tenant/interests'
      preLoaderRoute: typeof TenantInterestsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/messages': {
      id: '/tenant/messages'
      path: '/messages'
      fullPath: '/tenant/messages'
      preLoaderRoute: typeof TenantMessagesRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/saved': {
      id: '/tenant/saved'
      path: '/saved'
      fullPath: '/tenant/saved'
      preLoaderRoute: typeof TenantSavedRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/visits': {
      id: '/tenant/visits'
      path: '/visits'
      fullPath: '/tenant/visits'
      preLoaderRoute: typeof TenantVisitsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/owner/messages/$conversationId': {
      id: '/owner/messages/$conversationId'
      path: '/$conversationId'
      fullPath: '/owner/messages/$conversationId'
      preLoaderRoute: typeof OwnerMessagesConversationIdRouteImport
      parentRoute: typeof OwnerMessagesRoute
    }
    '/property/$propertyId/interest': {
      id: '/property/$propertyId/interest'
      path: '/interest'
      fullPath: '/property/$propertyId/interest'
      preLoaderRoute: typeof PropertyPropertyIdInterestRouteImport
      parentRoute: typeof PropertyPropertyIdRoute
    }
    '/tenant/interests/$interestId': {
      id: '/tenant/interests/$interestId'
      path: '/$interestId'
      fullPath: '/tenant/interests/$interestId'
      preLoaderRoute: typeof TenantInterestsInterestIdRouteImport
      parentRoute: typeof TenantInterestsRoute
    }
    '/tenant/messages/$conversationId': {
      id: '/tenant/messages/$conversationId'
      path: '/$conversationId'
      fullPath: '/tenant/messages/$conversationId'
      preLoaderRoute: typeof TenantMessagesConversationIdRouteImport
      parentRoute: typeof TenantMessagesRoute
    }
  }
}

interface OwnerMessagesRouteChildren {
  OwnerMessagesConversationIdRoute: typeof OwnerMessagesConversationIdRoute
}

const OwnerMessagesRouteChildren: OwnerMessagesRouteChildren = {
  OwnerMessagesConversationIdRoute: OwnerMessagesConversationIdRoute,
}

const OwnerMessagesRouteWithChildren = OwnerMessagesRoute._addFileChildren(
  OwnerMessagesRouteChildren,
)

interface OwnerRouteChildren {
  OwnerInterestsRoute: typeof OwnerInterestsRoute
  OwnerMessagesRoute: typeof OwnerMessagesRouteWithChildren
  OwnerPropertiesRoute: typeof OwnerPropertiesRoute
  OwnerVisitsRoute: typeof OwnerVisitsRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerInterestsRoute: OwnerInterestsRoute,
  OwnerMessagesRoute: OwnerMessagesRouteWithChildren,
  OwnerPropertiesRoute: OwnerPropertiesRoute,
  OwnerVisitsRoute: OwnerVisitsRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

interface TenantInterestsRouteChildren {
  TenantInterestsInterestIdRoute: typeof TenantInterestsInterestIdRoute
}

const TenantInterestsRouteChildren: TenantInterestsRouteChildren = {
  TenantInterestsInterestIdRoute: TenantInterestsInterestIdRoute,
}

const TenantInterestsRouteWithChildren = TenantInterestsRoute._addFileChildren(
  TenantInterestsRouteChildren,
)

interface TenantMessagesRouteChildren {
  TenantMessagesConversationIdRoute: typeof TenantMessagesConversationIdRoute
}

const TenantMessagesRouteChildren: TenantMessagesRouteChildren = {
  TenantMessagesConversationIdRoute: TenantMessagesConversationIdRoute,
}

const TenantMessagesRouteWithChildren = TenantMessagesRoute._addFileChildren(
  TenantMessagesRouteChildren,
)

interface TenantRouteChildren {
  TenantInterestsRoute: typeof TenantInterestsRouteWithChildren
  TenantMessagesRoute: typeof TenantMessagesRouteWithChildren
  TenantSavedRoute: typeof TenantSavedRoute
  TenantVisitsRoute: typeof TenantVisitsRoute
}

const TenantRouteChildren: TenantRouteChildren = {
  TenantInterestsRoute: TenantInterestsRouteWithChildren,
  TenantMessagesRoute: TenantMessagesRouteWithChildren,
  TenantSavedRoute: TenantSavedRoute,
  TenantVisitsRoute: TenantVisitsRoute,
}

const TenantRouteWithChildren =
  TenantRoute._addFileChildren(TenantRouteChildren)

interface PropertyPropertyIdRouteChildren {
  PropertyPropertyIdInterestRoute: typeof PropertyPropertyIdInterestRoute
}

const PropertyPropertyIdRouteChildren: PropertyPropertyIdRouteChildren = {
  PropertyPropertyIdInterestRoute: PropertyPropertyIdInterestRoute,
}

const PropertyPropertyIdRouteWithChildren =
  PropertyPropertyIdRoute._addFileChildren(PropertyPropertyIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgentRoute: AgentRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FlatmatesRoute: FlatmatesRoute,
  HowItWorksRoute: HowItWorksRoute,
  ListPropertyRoute: ListPropertyRoute,
  LocalitiesRoute: LocalitiesRoute,
  OwnerRoute: OwnerRouteWithChildren,
  RentRoute: RentRoute,
  SafetyRoute: SafetyRoute,
  TenantRoute: TenantRouteWithChildren,
  DashboardAgentRoute: DashboardAgentRoute,
  DashboardOwnerRoute: DashboardOwnerRoute,
  DashboardTenantRoute: DashboardTenantRoute,
  LegalCommunityGuidelinesRoute: LegalCommunityGuidelinesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  PropertyPropertyIdRoute: PropertyPropertyIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
