/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FlatmatesRouteImport } from './routes/flatmates'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ListPropertyRouteImport } from './routes/list-property'
import { Route as LocalitiesRouteImport } from './routes/localities'
import { Route as RentRouteImport } from './routes/rent'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as DashboardAgentRouteImport } from './routes/dashboard.agent'
import { Route as DashboardOwnerRouteImport } from './routes/dashboard.owner'
import { Route as DashboardTenantRouteImport } from './routes/dashboard.tenant'
import { Route as LegalCommunityGuidelinesRouteImport } from './routes/legal.community-guidelines'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as PropertyPropertyIdRouteImport } from './routes/property.$propertyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FlatmatesRoute = FlatmatesRouteImport.update({
  id: '/flatmates',
  path: '/flatmates',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ListPropertyRoute = ListPropertyRouteImport.update({
  id: '/list-property',
  path: '/list-property',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalitiesRoute = LocalitiesRouteImport.update({
  id: '/localities',
  path: '/localities',
  getParentRoute: () => rootRouteImport,
} as any)
const RentRoute = RentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAgentRoute = DashboardAgentRouteImport.update({
  id: '/dashboard/agent',
  path: '/dashboard/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOwnerRoute = DashboardOwnerRouteImport.update({
  id: '/dashboard/owner',
  path: '/dashboard/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTenantRoute = DashboardTenantRouteImport.update({
  id: '/dashboard/tenant',
  path: '/dashboard/tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCommunityGuidelinesRoute =
  LegalCommunityGuidelinesRouteImport.update({
    id: '/legal/community-guidelines',
    path: '/legal/community-guidelines',
    getParentRoute: () => rootRouteImport,
  } as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyPropertyIdRoute = PropertyPropertyIdRouteImport.update({
  id: '/property/$propertyId',
  path: '/property/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/flatmates': typeof FlatmatesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/list-property': typeof ListPropertyRoute
  '/localities': typeof LocalitiesRoute
  '/rent': typeof RentRoute
  '/safety': typeof SafetyRoute
  '/dashboard/agent': typeof DashboardAgentRoute
  '/dashboard/owner': typeof DashboardOwnerRoute
  '/dashboard/tenant': typeof DashboardTenantRoute
  '/legal/community-guidelines': typeof LegalCommunityGuidelinesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/property/$propertyId': typeof PropertyPropertyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/flatmates': typeof FlatmatesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/list-property': typeof ListPropertyRoute
  '/localities': typeof LocalitiesRoute
  '/rent': typeof RentRoute
  '/safety': typeof SafetyRoute
  '/dashboard/agent': typeof DashboardAgentRoute
  '/dashboard/owner': typeof DashboardOwnerRoute
  '/dashboard/tenant': typeof DashboardTenantRoute
  '/legal/community-guidelines': typeof LegalCommunityGuidelinesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/property/$propertyId': typeof PropertyPropertyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/flatmates': typeof FlatmatesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/list-property': typeof ListPropertyRoute
  '/localities': typeof LocalitiesRoute
  '/rent': typeof RentRoute
  '/safety': typeof SafetyRoute
  '/dashboard/agent': typeof DashboardAgentRoute
  '/dashboard/owner': typeof DashboardOwnerRoute
  '/dashboard/tenant': typeof DashboardTenantRoute
  '/legal/community-guidelines': typeof LegalCommunityGuidelinesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/property/$propertyId': typeof PropertyPropertyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/flatmates'
    | '/how-it-works'
    | '/list-property'
    | '/localities'
    | '/rent'
    | '/safety'
    | '/dashboard/agent'
    | '/dashboard/owner'
    | '/dashboard/tenant'
    | '/legal/community-guidelines'
    | '/legal/privacy'
    | '/legal/terms'
    | '/property/$propertyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/flatmates'
    | '/how-it-works'
    | '/list-property'
    | '/localities'
    | '/rent'
    | '/safety'
    | '/dashboard/agent'
    | '/dashboard/owner'
    | '/dashboard/tenant'
    | '/legal/community-guidelines'
    | '/legal/privacy'
    | '/legal/terms'
    | '/property/$propertyId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/flatmates'
    | '/how-it-works'
    | '/list-property'
    | '/localities'
    | '/rent'
    | '/safety'
    | '/dashboard/agent'
    | '/dashboard/owner'
    | '/dashboard/tenant'
    | '/legal/community-guidelines'
    | '/legal/privacy'
    | '/legal/terms'
    | '/property/$propertyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FlatmatesRoute: typeof FlatmatesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ListPropertyRoute: typeof ListPropertyRoute
  LocalitiesRoute: typeof LocalitiesRoute
  RentRoute: typeof RentRoute
  SafetyRoute: typeof SafetyRoute
  DashboardAgentRoute: typeof DashboardAgentRoute
  DashboardOwnerRoute: typeof DashboardOwnerRoute
  DashboardTenantRoute: typeof DashboardTenantRoute
  LegalCommunityGuidelinesRoute: typeof LegalCommunityGuidelinesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  PropertyPropertyIdRoute: typeof PropertyPropertyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flatmates': {
      id: '/flatmates'
      path: '/flatmates'
      fullPath: '/flatmates'
      preLoaderRoute: typeof FlatmatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-property': {
      id: '/list-property'
      path: '/list-property'
      fullPath: '/list-property'
      preLoaderRoute: typeof ListPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/localities': {
      id: '/localities'
      path: '/localities'
      fullPath: '/localities'
      preLoaderRoute: typeof LocalitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent': {
      id: '/rent'
      path: '/rent'
      fullPath: '/rent'
      preLoaderRoute: typeof RentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/agent': {
      id: '/dashboard/agent'
      path: '/dashboard/agent'
      fullPath: '/dashboard/agent'
      preLoaderRoute: typeof DashboardAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/owner': {
      id: '/dashboard/owner'
      path: '/dashboard/owner'
      fullPath: '/dashboard/owner'
      preLoaderRoute: typeof DashboardOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tenant': {
      id: '/dashboard/tenant'
      path: '/dashboard/tenant'
      fullPath: '/dashboard/tenant'
      preLoaderRoute: typeof DashboardTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/community-guidelines': {
      id: '/legal/community-guidelines'
      path: '/legal/community-guidelines'
      fullPath: '/legal/community-guidelines'
      preLoaderRoute: typeof LegalCommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$propertyId': {
      id: '/property/$propertyId'
      path: '/property/$propertyId'
      fullPath: '/property/$propertyId'
      preLoaderRoute: typeof PropertyPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FlatmatesRoute: FlatmatesRoute,
  HowItWorksRoute: HowItWorksRoute,
  ListPropertyRoute: ListPropertyRoute,
  LocalitiesRoute: LocalitiesRoute,
  RentRoute: RentRoute,
  SafetyRoute: SafetyRoute,
  DashboardAgentRoute: DashboardAgentRoute,
  DashboardOwnerRoute: DashboardOwnerRoute,
  DashboardTenantRoute: DashboardTenantRoute,
  LegalCommunityGuidelinesRoute: LegalCommunityGuidelinesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  PropertyPropertyIdRoute: PropertyPropertyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
